# Generated by Django 4.2.2 on 2023-06-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiqim',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='maosh',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='sotuv',
            name='deleted',
        ),
    ]
