# Generated by Django 4.2.2 on 2023-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApp', '0002_remove_chiqim_deleted_remove_maosh_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='miqdor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='maosh',
            name='miqdor',
            field=models.PositiveIntegerField(),
        ),
    ]
