# Generated by Django 4.2.2 on 2023-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_mahsulot_tarqatish_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot_tarqatish',
            name='miqdor',
            field=models.PositiveIntegerField(),
        ),
    ]
