# Generated by Django 4.2.2 on 2023-06-19 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ism', models.CharField(max_length=150)),
                ('fam', models.CharField(blank=True, max_length=150, null=True)),
                ('tel', models.CharField(max_length=13)),
                ('kpi', models.FloatField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to='mainApp.ombor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
